### ISSUE TITLE
[Feature Request] [PipeNet] New Comp allowing a resource processor to use multiple source pipelines

### ISSUE THREAD

**Issue by databobek** [Vanilla-Expanded/VanillaExpandedFramework#55] opened 2023-08-12 20:30 UTC
I think it would be cool to have a PipeNet Comp that would allow us to create refineries taking multiple resources as input. The XML could look something like this:

![image](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/assets/26349586/4df3f60b-175c-4de0-a1b9-0107f31eb1e8)

that would allow to make for more interesting pipes, for example refinery taking both Chemfuel and Helixien Gas to produce some raw plastics.

**Comment by KylianB** [comment] 2023-09-07 15:42
Added a new comp (WIP, but already working).
```xml
<li Class="PipeSystem.CompProperties_AdvancedResourceProcessor">
  <showBufferInfo>false</showBufferInfo>
  <notWorkingKey>VCHE_CantRefine</notWorkingKey>
  <progressBarOffset>(0, 0, -0.65)</progressBarOffset>
  <showResultItem>true</showResultItem>
  <processes>
    <li>VCHE_ProcessChemfuel</li>
  </processes>
  <soundAmbient>VCHE_RefineryAmbient</soundAmbient>
</li>
```

And the new def:
```xml
<PipeSystem.ProcessDef>
  <defName>VCHE_ProcessChemfuel</defName>
  <label>Make chemfuel</label>
  <ingredients>
    <li>
      <pipeNet>VCHE_DeepchemNet</pipeNet>
      <thing>VCHE_Deepchem</thing>
      <countNeeded>1</countNeeded>
    </li>
  </ingredients>
  <!-- Result: -->
  <ticks>30000</ticks>
  <pipeNet>VCHE_ChemfuelNet</pipeNet>
  <thing>Chemfuel</thing>
  <count>3</count>
  <destroyIngredientsDirectly>true</destroyIngredientsDirectly>
</PipeSystem.ProcessDef>
```

For now there is no wiki page for it (things may change, be added…). More info on the usable tags can be found in [CompProperties_AdvancedResourceProcessor.cs](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/blob/main/Source/PipeSystem/PipeSystem/Comps/CompProperties/CompProperties_AdvancedResourceProcessor.cs) and [ProcessDef.cs](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/blob/main/Source/PipeSystem/PipeSystem/Def/ProcessDef.cs).

I will let this thread open for suggestion and report on how it works!

**Comment by databobek** [comment] 2023-09-07 15:50
I’ll check it out tonight and let you know, madlad!

**Comment by databobek** [comment] 2023-09-07 16:20
Aawww

```
Exception in ConfigErrors() of VCEPU_PrometheumRefinery: System.NullReferenceException: Object reference not set to an instance of an object
  at PipeSystem.CompProperties_AdvancedResourceProcessor+<ConfigErrors>d__11.MoveNext () [0x000fa] in <246c58623a5141fe9a9a92932c2c3248>:0 
  at Verse.ThingDef+<ConfigErrors>d__352.MoveNext () [0x00e09] in <95de19971c5d40878d8742747904cdcd>:0 
  at Verse.DefDatabase`1[T].ErrorCheckAllDefs () [0x0006b] in <95de19971c5d40878d8742747904cdcd>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.DefDatabase`1<Verse.ThingDef>:ErrorCheckAllDefs ()
System.Reflection.MonoMethod:Invoke (object,System.Reflection.BindingFlags,System.Reflection.Binder,object[],System.Globalization.CultureInfo)
System.Reflection.MethodBase:Invoke (object,object[])
Verse.GenGeneric:InvokeStaticMethodOnGenericType (System.Type,System.Type,string)
Verse.PlayDataLoader/<>c:<DoPlayLoad>b__4_1 (System.Type)
System.Threading.Tasks.Parallel/<>c__DisplayClass31_0`2<System.Type, object>:<ForEachWorker>b__0 (int)
System.Threading.Tasks.Parallel/<>c__DisplayClass17_0`1<object>:<ForWorker>b__1 ()
System.Threading.Tasks.Task:InnerInvoke ()
System.Threading.Tasks.Task:InnerInvokeWithArg (System.Threading.Tasks.Task)
System.Threading.Tasks.Task/<>c__DisplayClass178_0:<ExecuteSelfReplicating>b__0 (object)
System.Threading.Tasks.Task:InnerInvoke ()
System.Threading.Tasks.Task:Execute ()
System.Threading.Tasks.Task:ExecutionContextCallback (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.Tasks.Task:ExecuteWithThreadLocal (System.Threading.Tasks.Task&)
System.Threading.Tasks.Task:ExecuteEntry (bool)
System.Threading.Tasks.Task:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem ()
System.Threading.ThreadPoolWorkQueue:Dispatch ()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback ()

```

  ```
   <li Class="PipeSystem.CompProperties_AdvancedResourceProcessor">
        <showBufferInfo>false</showBufferInfo>
        <notWorkingKey>VCEPU_CantRefinePrometheum</notWorkingKey>
        <progressBarOffset>(0, 0, -0.65)</progressBarOffset>
        <showResultItem>true</showResultItem>
        <processes>
          <li>VCHEPU_RefineIntoPrometheum</li>
        </processes>
        <soundAmbient>VCHE_RefineryAmbient</soundAmbient>
      </li>
```

```

<PipeSystem.ProcessDef>
    <defName>VCHEPU_RefineIntoPrometheum</defName>
    <label>Make Prometheum</label>
    <ingredients>
      <li>
        <pipeNet>VHGE_HelixienNet</pipeNet>
        <thing>VHGE_Helixien</thing>
        <countNeeded>10</countNeeded>
      </li>
      <li>
        <pipeNet>VCHE_ChemfuelNet</pipeNet>
        <thing>Chemfuel</thing>
        <countNeeded>5</countNeeded>
      </li>
    </ingredients>
    <!-- Result: -->
    <ticks>15000</ticks>
    <pipeNet>VCEPU_PrometheumNet</pipeNet>
    <thing>Prometheum</thing>
    <count>3</count>
    <destroyIngredientsDirectly>true</destroyIngredientsDirectly>
  </PipeSystem.ProcessDef>
```

![image](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/assets/26349586/005b13e8-366d-4db0-b66c-6cad683fd7d2)

**Comment by databobek** [comment] 2023-09-07 17:30
https://gist.github.com/HugsLibRecordKeeper/291acea04544bc6225efed887cf57f77

here you go friend

**Comment by KylianB** [comment] 2023-09-07 18:27
Thank you, could you try to add to your def:
```xml
<inspectorTabs>
  <li>PipeSystem.ITab_Processor</li>
</inspectorTabs>
```
Also make sure you have the needed comp resource, the new processor doesn't act as one. In your case, you seem to need:
```xml
<li Class="PipeSystem.CompProperties_Resource">
  <pipeNet>VCHE_ChemfuelNet</pipeNet>
</li>
<li Class="PipeSystem.CompProperties_Resource">
  <pipeNet>VHGE_HelixienNet</pipeNet>
</li>
```

**Comment by databobek** [comment] 2023-09-08 06:17
This is so cool man!

I'll change my Defs to use the new system and let you know how it works in some time.

**Comment by databobek** [comment] 2023-09-08 09:28
First thoughts:
Would be cool if I am building a refinery connecting to many pipelines that it would highlihgt all connectable pipes on map (not only output pipe and power conduits.

I really dig that it shows what it is producing instead of the giant progress bar. Maybe optionally also allow to show the source resources?

The ongoing process label in the process inspector tab could use a bit more space.
![image](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/assets/26349586/709cae7e-fd42-4cf7-b3bb-7049555d91ac)

Not sure how that happens:
![image](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/assets/26349586/37c5f2b2-4d6e-4992-ac65-a51003e78ec0)
If you have an ongoing process and remove the bill, it goes into negatives :)

**Comment by databobek** [comment] 2023-09-08 09:49
Not sure if process def accepts research requirement but that would be awesome as well :)

**Comment by databobek** [comment] 2023-09-08 10:09
Doesn't seem i can use this to drop things on the ground? Cause i get a config error without result pipe system

**Comment by databobek** [comment] 2023-09-08 11:57
When result tank/network is full, the production should stop I think, but it just drops on the ground

**Comment by KylianB** [comment] 2023-09-08 12:07
> First thoughts: Would be cool if I am building a refinery connecting to many pipelines that it would highlihgt all connectable pipes on map (not only output pipe and power conduits.
> 
> I really dig that it shows what it is producing instead of the giant progress bar. Maybe optionally also allow to show the source resources?
> 
> The ongoing process label in the process inspector tab could use a bit more space. ![image](https://user-images.githubusercontent.com/26349586/266566221-709cae7e-fd42-4cf7-b3bb-7049555d91ac.png)
> 
> Not sure how that happens: ![image](https://user-images.githubusercontent.com/26349586/266566392-37c5f2b2-4d6e-4992-ac65-a51003e78ec0.png) If you have an ongoing process and remove the bill, it goes into negatives :)

Will try to reproduce and fix, thank you. Same thing for the UI issue.

> Not sure if process def accepts research requirement but that would be awesome as well :)

Not yet, but I can add it

> Doesn't seem i can use this to drop things on the ground? Cause i get a config error without result pipe system

It should be possible when having only `<thing>Prometheum</thing>` in your processed def (and no `<pipeNet>VCEPU_PrometheumNet</pipeNet>`)

> When result tank/network is full, the production should stop I think, but it just drops on the ground

It's planned to be a processor option, somewhere in the UI. By default, it won't spawn if the net is full, but the player will also be able to make it spawn on ground when the net is full.

Thank you for all the feedback!

**Comment by databobek** [comment] 2023-09-08 15:58
> somewhere in the UI
I like

> Should be possible

doesn't work for me
![image](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/assets/26349586/3ca8990e-159d-45e6-be50-ffd248229f58)
![image](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/assets/26349586/7d69921c-8b3b-46a9-89fb-6ac6bd7587c5)

https://gist.github.com/HugsLibRecordKeeper/9b713e957e632e934f7faa93dc5926be

**Comment by databobek** [comment] 2023-09-09 07:32
![image](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/assets/26349586/53870d4c-6ebd-4d15-9985-95c335e9f029)
seems that they still check for hauling jobs even if piped? spams the logs a bit with many refineries :)

**Comment by databobek** [comment] 2023-09-11 08:59
After the recent changes:
![image](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/assets/26349586/e253fc7c-1232-4867-98e3-4a8924b475ca)
Log spam is still there ( i guess for debug?)

![image](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/assets/26349586/f7073227-ecfc-4e96-a98e-7ae334188088)

still goes into negative (not a big issue tbh) [reproduce by: add process (x10), process starts, reduce count to x0, process ends, process count now is x -1) Happens also when removing and readding the process

Production setting on the ground/ or not correctly chooses pipe or ground vs pipe or stop  ✓
I'd rename the setting to "Continue production when net full" cause now it kinda implies pipe or ground IMO.

The list of processes doesn't choose the first available process
![image](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/assets/26349586/f7e8f96d-98aa-402a-8d5b-8efd10145505)
In this case, the refinery was connected to everything required for "Make Dye from Waste", but the first process was already started, which makes it impossible to have fallback pipelines :)

You can have refineries with mixed manual/piped input!! ✓
![image](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/assets/26349586/a012133b-b941-49e2-968a-97d9c5852a1b)

If i configure like this:
![image](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/assets/26349586/142f82d6-e527-43d4-a476-ace1851ac784)
It will just take the "steel" from the net, which doesn't really make sense. Maybe skip the "thing" entirely if pipenet is defined?

**Comment by KylianB** [comment] 2023-09-11 13:39
Going to fix the above issues, thank you!
For the ingredients, this is the intended behaviour. If the processor can take from the net it will do so, if it can't, pawns will try to fill it using a map item. When used together as a single ingredient, they are intended to represent the same thing.

**Comment by databobek** [comment] 2023-09-11 13:40
I already remade both my pipeline mods to fit into this :) it's great work Kylian

**Comment by databobek** [comment] 2023-09-14 09:13
Would be cool if the process clearly showed whether it's started or not + how much time each process takes :)

**Comment by databobek** [comment] 2023-09-29 19:16
![image](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/assets/26349586/7df529c6-d254-4fbe-99d2-97137a80f336)
ultra super based

**Comment by databobek** [comment] 2023-10-10 06:20
![image](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/assets/26349586/0217263f-8860-4bf4-9232-287674978ed9)
guess this should be hidden behind dev mode? :)

**Comment by databobek** [comment] 2023-10-15 12:12
I've used this extensively over the past weeks and there seem to be no outstanding issues.

Hopefully this month I will release a mod that uses it so we'll get more testers :)

Only outstanding things imo is:

* Adding a researchPrerequisite to a ProcessDef, so that we can improve them not only horizontally (more refineries) but also vertically (better processing techniques).
* Removing the log messages spamming the console :)
![image](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/assets/26349586/b5ae406a-8eb9-4ac7-91b1-661ef66fdb60)

**Comment by databobek** [comment] 2023-12-19 11:35
Seems that if I have a networked item and a manual item, after reloading a save they need to be refilled (progress doesn't fall though).

**Comment by databobek** [comment] 2023-12-29 09:35
![image](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/assets/26349586/03e9973d-fc3d-4b7d-99ca-1961b0f37bc8)
![image](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/assets/26349586/cc8d6fec-9dde-4d2f-a34c-cf55a1a78bae)
The label is not used

**Comment by databobek** [comment] 2023-12-29 10:40
When  wastepack container is full, the next processes continue as normal without filling the wastepack container anymore

**Comment by databobek** [comment] 2023-12-30 15:45
When there are no processes available, it goes into red error when pressing the "add process" button.

When you have the resource specified as ingredient
![image](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/assets/26349586/bfea1960-f43d-43e1-9954-35cf97d99b24)
it tries to find the texture by name and fails (because these are multi-folders, not graphic2d)

**Comment by KylianB** [comment] 2024-01-07 18:44
> Seems that if I have a networked item and a manual item in a process definition, after reloading a save they need to be refilled (progress doesn't fall though).

Should be fixed

> The label is not used

It's used inside the process tab, when it's the current process

> When wastepack container is full, the next processes continue as normal without filling the wastepack container anymore

It's the default behaviour (copying vanilla), but it can be modified with `<stopWhenWastepackFull>true</stopWhenWastepackFull>` (on the `CompProperties_AdvancedResourceProcessor`)

> When there are no processes available, it goes into red error when pressing the "add process" button.

Should be fixed

**Comment by databobek** [comment] 2024-01-28 21:14
![image](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/assets/26349586/7d62a4c3-6659-4ea3-a2e0-2707f471ef2b)
Shows "Contents: Nothing" when waster container is set and waste % only shows when process is working

**Comment by databobek** [comment] 2024-02-04 12:17
It seems that the refineries cannot be cleared of waste
![image](https://github.com/Vanilla-Expanded/VanillaExpandedFramework/assets/26349586/2054b129-11cf-4245-ab29-882af361fe9d)
even though rechargers can

**Comment by databobek** [comment] 2024-02-10 19:39
Seems the comp crashes without biotech (NRE)

**Comment by databobek** [comment] 2024-02-11 10:27
stop when wastepack full doesn't seem to stop processing when waste is at 100%, might be linked to the double waste container thing?

**Closed** 2024-05-05 11:18 UTC
Labels: enhancement, WIP
